version: "3"

services:
  my_characters_frontend:
    container_name: my_characters_frontend
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile
    volumes:
      - ../frontend:/app
      - app/node_modules
    ports:
      - "3300:8080"
